services:
  - type: web
    name: flapware
    env: python
    repo: https://github.com/KnowYourLines/flapware.git
    region: ohio
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt; python manage.py makemigrations blabhear; python manage.py migrate; python manage.py collectstatic --no-input"
    startCommand: "daphne server.asgi:application --bind 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: flapware.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: flapware-db
          property: connectionString

databases:
  - name: flapware-db
    plan: free
    region: ohio
    postgresMajorVersion: 14
    ipAllowList: [] # only allow internal connections
