services:
  - type: web
    name: veyfly
    env: python
    repo: https://github.com/KnowYourLines/veyfly.git
    region: ohio
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt; python manage.py makemigrations veyfly; python manage.py migrate; python manage.py collectstatic --no-input"
    startCommand: "daphne server.asgi:application --bind 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: veyfly.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: veyfly-db
          property: connectionString
      - key: AMADEUS_API_KEY
        sync: false
      - key: AMADEUS_API_SECRET
        sync: false
      - key: AMADEUS_BASE_URL
        sync: false

databases:
  - name: veyfly-db
    plan: free
    region: ohio
    postgresMajorVersion: 14
    ipAllowList: [] # only allow internal connections
